# Generated by Django 4.2.7 on 2024-02-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_topic_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='first_app.user'),
        ),
    ]
